"""initial schema

Revision ID: 030384c06dd9
Revises: 
Create Date: 2026-09-01 13:45:10.395386
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '030384c06dd9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('marvel_event_id', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('curation_status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('series_name', sa.String(length=200), nullable=False),
    sa.Column('series_slug', sa.String(length=200), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('marvel_com_issue_id', sa.Integer(), nullable=True),
    sa.Column('digital_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('unison_drn', sa.String(length=120), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_extension', sa.String(length=10), nullable=True),
    sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('unavailable_note', sa.Text(), server_default='', nullable=False),
    sa.Column('provisional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_slug', 'issue_number', name='uq_issue_series_number')
    )
    op.create_index(op.f('ix_issues_key'), 'issues', ['key'], unique=True)
    op.create_index(op.f('ix_issues_marvel_com_issue_id'), 'issues', ['marvel_com_issue_id'], unique=False)
    op.create_index(op.f('ix_issues_series_slug'), 'issues', ['series_slug'], unique=False)
    op.create_table('marvel_response_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('params_key', sa.String(length=500), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('etag', sa.String(length=120), server_default='', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attribution_text', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', 'params_key', name='uq_cache_endpoint_params')
    )
    op.create_index(op.f('ix_marvel_response_cache_endpoint'), 'marvel_response_cache', ['endpoint'], unique=False)
    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=255), server_default='', nullable=False),
    sa.Column('used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_authorization_codes_client_id'), 'oauth_authorization_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_code_hash'), 'oauth_authorization_codes', ['code_hash'], unique=True)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=255), server_default='', nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_access_token_hash'), 'oauth_tokens', ['access_token_hash'], unique=True)
    op.create_index(op.f('ix_oauth_tokens_client_id'), 'oauth_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_refresh_token_hash'), 'oauth_tokens', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('oauth_subject', sa.String(length=255), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('event_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('narrative_role', sa.String(length=20), nullable=False),
    sa.Column('franchise', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'issue_id', name='uq_event_issue'),
    sa.UniqueConstraint('event_id', 'position', name='uq_event_position')
    )
    op.create_index(op.f('ix_event_issues_event_id'), 'event_issues', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_issues_issue_id'), 'event_issues', ['issue_id'], unique=False)
    op.create_table('issue_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_issue_id', sa.UUID(), nullable=False),
    sa.Column('to_issue_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('omnibus_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_issue_id', 'to_issue_id', 'relation_type', name='uq_reference_edge')
    )
    op.create_index(op.f('ix_issue_references_from_issue_id'), 'issue_references', ['from_issue_id'], unique=False)
    op.create_index(op.f('ix_issue_references_to_issue_id'), 'issue_references', ['to_issue_id'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('redirect_uris', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth_clients_user_id'), 'oauth_clients', ['user_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), server_default='', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('event_slug', sa.String(length=100), server_default='', nullable=False),
    sa.Column('event_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='', nullable=False),
    sa.Column('narrative_role', sa.String(length=20), server_default='', nullable=False),
    sa.Column('franchise', sa.String(length=20), server_default='', nullable=False),
    sa.Column('series_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_extension', sa.String(length=10), nullable=True),
    sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('digital_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('source_reference_id', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.Text(), server_default='', nullable=False),
    sa.Column('omnibus_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_reference_id'], ['issue_references.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_issue_id'), 'bookmarks', ['issue_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_status'), 'bookmarks', ['status'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('shelf_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_bookmark_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_bookmark_id'], ['bookmarks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_candidates_user_id'), 'shelf_candidates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelf_candidates_user_id'), table_name='shelf_candidates')
    op.drop_table('shelf_candidates')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_status'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_issue_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_created_at'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_oauth_clients_user_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_issue_references_to_issue_id'), table_name='issue_references')
    op.drop_index(op.f('ix_issue_references_from_issue_id'), table_name='issue_references')
    op.drop_table('issue_references')
    op.drop_index(op.f('ix_event_issues_issue_id'), table_name='event_issues')
    op.drop_index(op.f('ix_event_issues_event_id'), table_name='event_issues')
    op.drop_table('event_issues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_refresh_token_hash'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_client_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_access_token_hash'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_oauth_authorization_codes_code_hash'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_client_id'), table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_index(op.f('ix_marvel_response_cache_endpoint'), table_name='marvel_response_cache')
    op.drop_table('marvel_response_cache')
    op.drop_index(op.f('ix_issues_series_slug'), table_name='issues')
    op.drop_index(op.f('ix_issues_marvel_com_issue_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_key'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
