"""add session csrf token

Revision ID: 15cfdbefc5c2
Revises: f8290a774a04
Create Date: 2026-09-01 20:01:09.168337
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '15cfdbefc5c2'
down_revision: str | None = 'f8290a774a04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_sessions',
        sa.Column('csrf_token', sa.String(length=64), server_default='', nullable=False),
    )
    # Backfill. An existing session with an empty token would be authenticated
    # but have nothing to compare against, and the CSRF check treats "no token"
    # as "nothing to protect" — so a pre-migration session would silently skip
    # it. Giving every row a value closes that window; readers keep their
    # sessions rather than being signed out by a deploy.
    # gen_random_uuid() is built into Postgres 13+; gen_random_bytes() would
    # need the pgcrypto extension, which a Heroku Essential database does not
    # have enabled by default. Two UUIDs give 64 hex characters, which is the
    # column width and ample for a CSRF token.
    op.execute(
        "UPDATE user_sessions SET csrf_token = "
        "replace(gen_random_uuid()::text, '-', '') || "
        "replace(gen_random_uuid()::text, '-', '') "
        "WHERE csrf_token = ''"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'csrf_token')
    # ### end Alembic commands ###
