"""add digital_id_source provenance

Revision ID: 1a43be928948
Revises: 030384c06dd9
Create Date: 2026-09-01 17:41:41.965201
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1a43be928948'
down_revision: str | None = '030384c06dd9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('digital_id_source', sa.String(length=80), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'digital_id_source')
    # ### end Alembic commands ###
