"""add bookmark unlimited_on

Revision ID: ba0a0f48e438
Revises: f4a5acbf8124
Create Date: 2026-09-02 15:46:19.147814
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ba0a0f48e438'
down_revision: str | None = 'f4a5acbf8124'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('unlimited_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'unlimited_on')
    # ### end Alembic commands ###
