"""add user password hash

Revision ID: c87534f1c47e
Revises: f270186d6e99
Create Date: 2026-09-02 14:24:59.215349
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c87534f1c47e'
down_revision: str | None = 'f270186d6e99'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
