"""add mirror response cache

Revision ID: f270186d6e99
Revises: 15cfdbefc5c2
Create Date: 2026-09-02 09:57:38.707947
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f270186d6e99'
down_revision: str | None = '15cfdbefc5c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mirror_response_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('params_key', sa.String(length=500), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', 'params_key', name='uq_mirror_cache_path_params')
    )
    op.create_index(op.f('ix_mirror_response_cache_fetched_at'), 'mirror_response_cache', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_mirror_response_cache_path'), 'mirror_response_cache', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mirror_response_cache_path'), table_name='mirror_response_cache')
    op.drop_index(op.f('ix_mirror_response_cache_fetched_at'), table_name='mirror_response_cache')
    op.drop_table('mirror_response_cache')
    # ### end Alembic commands ###
