"""add issue unlimited_on

Revision ID: f4a5acbf8124
Revises: c87534f1c47e
Create Date: 2026-09-02 15:44:25.136222
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f4a5acbf8124'
down_revision: str | None = 'c87534f1c47e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('unlimited_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'unlimited_on')
    # ### end Alembic commands ###
