"""add reader handle and admin flag

Revision ID: faef8885b67b
Revises: 1a43be928948
Create Date: 2026-09-01 19:26:20.952746
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'faef8885b67b'
down_revision: str | None = '1a43be928948'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Added nullable first, then backfilled, then tightened. Adding a UNIQUE
    # NOT NULL column straight away fails on any existing row: they would all
    # take the same empty-string default and collide on the unique index.
    op.add_column('users', sa.Column('handle', sa.String(length=32), nullable=True))
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    )

    # Backfill from the email local part, lowercased and stripped of anything
    # that cannot appear in an environment variable name — a handle names its
    # own password var, CROSSOVER_PASSWORD_{HANDLE}.
    op.execute(
        """
        UPDATE users
        SET handle = regexp_replace(lower(split_part(email, '@', 1)), '[^a-z0-9_]', '', 'g')
        WHERE handle IS NULL
        """
    )
    # A handle must start with a letter; prefix anything that does not.
    op.execute("UPDATE users SET handle = 'r' || handle WHERE handle !~ '^[a-z]'")
    # Disambiguate any collision the backfill created, so the unique index below
    # can be applied without a migration failure on real data.
    op.execute(
        """
        UPDATE users u SET handle = u.handle || substr(u.id::text, 1, 4)
        WHERE EXISTS (
            SELECT 1 FROM users other
            WHERE other.handle = u.handle AND other.id <> u.id
        )
        """
    )

    op.alter_column('users', 'handle', nullable=False)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'handle')
    # ### end Alembic commands ###
